### ISSUE TITLE
Konvertering feiler hvis konvertering er ferdig før brukeren trykker lagre

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/videoconverter#7]
videoconverteren har ingen måte å hente seg inn igjen hvis konverteringen er ferdig før brukeren trykker lagre.
Store-cron setter status transferrred, og first_convert = completed. Ettersom den ikke finner databaseinfo på UKM.no vet den ikke hva som skal skje med filen, og alt stopper opp.

En løsning kan være at UKM.no trigger et script på converteren ved lagring. Scriptet kan finne cronjobber som har status transferred+complete ut fra cron_id, og dermed fortsette konverteringen

**Comment by mariusmandal** [comment]
Å sette status_progress tilbake til store funker

**Comment by mariusmandal** [comment]
Det enkleste er å legge inn en curl mot videoconverter.ukm.no/api/uploaded.php (må opprettes) når brukeren lagrer videoreportasjer. Innslagsopplasting trigger submit() når upload complete. https://github.com/UKMNorge/UKMvideo/blob/master/save/save_video_reportasje_uploaded.inc.php#L31

## uploaded.php @ videoconverter/api/
- select from database where cron_id = GET[id] & status=transferred & first_convert=completet
- if num_rows == 1
- update (row) set `status`='store'

return void / always true

**Comment by AsgeirSH** [comment]
Videoconverter-subdomain ligger ikke i cPanel, hvor finner jeg brukerinfo etc?

**Comment by mariusmandal** [comment]
fixed
